language: objective-c
osx_image: xcode9.1
xcode_project: UnderLineTextField
xcode_scheme: UnderLineTextField
xcode_sdk: iphonesimulator9.1
env:
  global:
  - FRAMEWORK_NAME=UnderLineTextField
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script: 
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME

