language: objective-c
osx_image: xcode9.1
script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.1 -project UnderLineTextField.xcodeproj -scheme UnderLineTextField CODE_SIGNING_REQUIRED=NO
branches:
  only:
  - master
xcode_project: UnderLineTextField.xcodeproj
xcode_scheme: UnderLineTextField
xcode_sdk: iphonesimulator11.1
env:
  global:
  - FRAMEWORK_NAME=UnderLineTextField
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script: 
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
